### ISSUE TITLE
Your code is Segmentation fault occurring!! Please help me~

### ISSUE THREAD

**Issue by jenginsu** [alphacep/kaldi-websocket-python#7]
Hi? Mr. Nickolay

I can not speak English well. Sorry.

I am analyzing the source code. You provided it.
But a Segmentatin Fault is occurring.

I've been looking for a solution for a week, but can't find a solution.

So I write here.

My test environment
======================================
- Ubuntu 18.04.3 LTS
- Python3: 3.6.8, Python: 2.7.15+
- g ++ (Ubuntu 7.4.0-1ubuntu1 ~ 18.04.1) 7.4.0
- SWIG Version 4.0.1 (Configured options: + pcre)
- Kaldi Version: latest(Kaldi compile and decode process ALL OK.)
- Test file: see attached file (Only modify "Makefile", "model.cc" files)
======================================

Error details:
[helpme.zip](https://github.com/alphacep/kaldi-websocket-python/files/3582916/helpme.zip)

Segmentation Fault (core dumped) occurs in "from kaldi_recognizer import Model, KaldiRecognizer" section of "asr_server.py" file

Thank you.

attached file: (https://github.com/alphacep/kaldi-websocket-python/files/3582922/helpme.zip)

**Comment by nshmyrev** [comment]
Hi

please run it like this:

```valgrind python asr_server.py >& crash.log```

and provide the result

**Comment by jenginsu** [comment]
Thank you sir~

Here~
[crash.zip](https://github.com/alphacep/kaldi-websocket-python/files/3582963/crash.zip)

**Comment by nshmyrev** [comment]
Hi

According to this https://stackoverflow.com/questions/57064962/boost-python-own-module-throws-segmentation-fault-globalerrorpushtostack it might be caused by python version mismatch due to compilation and runtime. In makefile we are using pkgconfig to figure out python libraries - `pkg-config --libs python3`. Can you run from command line and compare with python version you are trying to use when you run the asr_server.py? Most likely you have many pythons in your system of different versions. You can edit makefile accordingly then.

**Comment by jenginsu** [comment]
I will check it!

Have nice weekend.

I'll come back Monday.

Thank you!

**Comment by attitudezoe** [comment]
Hi,
I also got the Segmentation fault error when run asr_server.py.  The crash log is here. 
[crash.log](https://github.com/alphacep/kaldi-websocket-python/files/3600319/crash.log)

How can I solve this problem?
Thank you!

**Comment by nshmyrev** [comment]
@attitudezoe this crash is likely caused by your modification to introduce const arpa which you need to share to get help. Also please do not jump into random thread, create another issue instead.

**Comment by nshmyrev** [comment]
No response yet, please reopen if needed.
